### ISSUE TITLE
Font-size for existing content in first Quill editor isn't taken

### ISSUE THREAD

**Issue by carsonbaker** [slab/quill#4119]
I'm re-submitting issue #3062 as it was closed for completion without being fixed. The bug still presents in Quill 2.0.0.

Issue #3234 duplicates the bug and was also closed.

--

When existing content is provided to several quill editor instances, the font-size property of the text is removed on the first Quill editor, even if the value is present in the Size.whitelist.

**Steps for Reproduction**

Visit https://jsfiddle.net/9cur3dmx

**Expected behavior:**

The font sizes should be the same in both editors.

**Actual behavior:**

Observe that the font size in the first Quill editor is different than the second.

**Platforms:**

Chrome 83.0.4103.61, MacOS
Chrome 122.0.6261.94, NixOS

**Version:**

Affects all Quill versions, including Quill 2.0.0, and 1.3.7.

**Comment by davidmold** [comment]
For your example, all you need to do is register the size before you create quill:
```
 function setupQuill(element) {

    var Size       = Quill.import('attributors/style/size');
    Size.whitelist = ['13px', '15px', '18px', '21px'];
		Quill.register(Size, true);
    
    const toolbarObj = [
        [{ 'size': ['13px', '15px', '18px', '21px'] }],
      ]

    const quill = new Quill(element, {
      modules: { toolbar: toolbarObj },
      theme: 'snow'
    });

    return quill;
  }
```
