### ISSUE TITLE
keyboard.addBinding for 13/Enter doesn't seem to have an effect

### ISSUE THREAD

**Issue by ile** [slab/quill#4247]
Adding these in [Playground](https://quilljs.com/playground/snow) doesn't seem to have an effect. Not sure if this is by design or not.

```js
quill.keyboard.addBinding({
    key: 13,
    shiftKey: true,
    handler: (range, context) => {
        console.log(range, context);
    }
});

quill.keyboard.addBinding({
    key: 'Enter',
    shiftKey: true,
    handler: (range, context) => {
        console.log(range, context);
    }
});
```

I'm trying to add functionality for Shift+Enter, for adding a newline or `<br>`: https://github.com/slab/quill/issues/1187

If there is some way to accomplish the `<br>` that would be great as well.

**Comment by lkalinowski** [comment]
We asked for help with this also in this issue: https://github.com/slab/quill/issues/4228

**Comment by ile** [comment]
I found the docs.

> However since bindings specified in the configuration will run before Quill's defaults, you can handle special cases and propagate to Quill's otherwise.
