### ISSUE TITLE
Link editing tooltip position is not proper

### ISSUE THREAD

**Issue by reuse-ay** [slab/quill#4256]
Link editing tooltip position is not proper. I also had trouble using the dialog. 

**Steps for Reproduction**

1. Visit quilljs.com
2. Select "Quill" in paragraph
3. Click link editing button
![スクリーンショット 2024-06-17 103902](https://github.com/slab/quill/assets/150884298/5dc0f8f7-dcf7-4da2-a865-6cfdd8965bf3)
This is use in dialog in my work.
![スクリーンショット 2024-06-17 105114](https://github.com/slab/quill/assets/150884298/c6989910-c0a9-4bde-b829-50e8999ebdac)

**Expected behavior**:
Tooltip's position should  be adjusted to the editor element.(probably class="ql-container")

**Actual behavior**:

Tooltip element doesn't fit the area.
"left" could get negative.

**Platforms**:

Chrome

**Version**:
My dialog sample is using 2.0.2

**Comment by FZ-Iskandar** [comment]
I have the same issue
