### ISSUE TITLE
getHTML/getSemanticHTML strips embed, replaces with hyperlink

### ISSUE THREAD

**Issue by enzedonline** [slab/quill#4280]
When using the video module to embed a YouTube clip, `quill.editor.getHTML(0, quill.getLenth())` or `quill.getSemanticHTML()` converts the iframe to a hyperlink.

**Steps for Reproduction**

[Quill playground link](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQCsDOIBcIDGB7KNAFwAIBHAVwgBtqSBeEqOAdxIEUraAKAcgGI4MCETwAnXgBoSwADpQSJALZ4YFanDSYZ8xYtF5qAIwCGY7QG1dexRd4A3CPDy8AupOuL31gL4eFJAAO1CY4cAAWhvDmJLwAwnhKgXhocCQmCnCBEDhIeVLWROFwSnDavGhQeCxSJGBgJOKxRhRGRhq88j4AlADc8viEpML2APIURIETDCQweDgUpVBESDhicCZEcACiGktEfCO8ffKUNNSrBEQm0HBiSNCpYkQAgjAooXDLuyVfB7wmABmW3WsFqI3GkwmJ1gEDGEymKy2CCICWWfxmvAAkoQ7qRHM5eP0oGdaEgCHxkUQALQ4cIZADmcFq3G6DAAfDoAooIQiJkgqWitssZqSLkyiABlEoZIg5AASABUALIAGVZxJ6vRAknA0HgyHCRCU1CwIAAPCMSE56LIQEIROI7ezzWARuz5PJzWg1hBAqQ0GIcLa9bBEKg0M7XT6xH6iOyQD4gA).

```javascript
const quill = new Quill('#editor', {
  modules: {
    toolbar: [
      ['video'],
    ],
  },
  placeholder: 'Compose an epic...',
  theme: 'snow', // or 'bubble'
});
const divOutput = document.createElement('div');
quill.container.insertAdjacentElement('afterend', divOutput);
divOutput.textContent = 'Insert video';
quill.on('text-change', () => {
    divOutput.textContent = quill.getSemanticHTML();
});
```
![image](https://github.com/slab/quill/assets/72310199/f6c11aab-c870-463c-829a-e930e7f3510e)

Example editor video html: 
```html
 <iframe 
  class="ql-video ql-iframe-align-right" 
  frameborder="0" allowfullscreen="true" 
  src="https://www.youtube.com/embed/eDRgzEVwVEc?showinfo=0" 
  height="270.27734436035155" width="542">
</iframe>
```

getSemanticHTML output:
```html
<a href="https://www.youtube.com/embed/eDRgzEVwVEc?showinfo=0"
  target="_blank" rel="nofollow noopener">
  https://www.youtube.com/embed/eDRgzEVwVEc?showinfo=0
</a>
```

**Expected behavior**: embeds and their attributes (i.e. src, height, width, classList etc) should be preserved 

**Actual behavior**: it's converted to an hyperlink. Outputting as a hyperlink makes `getHTML` and `getSemanticHTML()` unusable for its intended purpose since this should be a direct HTML representation of the editor contents.

**Platforms**: quilljs 2.0.2, windows 10, chrome

**Version**: 2.0.2

**Comment by enzedonline** [comment]
see #4829

**Comment by skillcapesoftware** [comment]
@enzedonline Your link is broken from the comment above to a potential fix. Could you reply with where to find the suggested workaround?

**Comment by enzedonline** [comment]
@skillcapesoftware weird, I can link to other issues in that comment but not that issue, but it works here ... #4289. 

This issue isn't resolved, it's just combined with a few other issues with `getSemanticHTML` listed on the other one. It's caused by the [html method](https://github.com/slab/quill/blob/b213e1073bac1478649f26e3c0dad50ad0eb2a49/packages/quill/src/formats/video.ts#L53-L56) of Quill's video embed.

The workaround for video is to create a custom embed extending the video embed and overriding the `html` method. Something like:

```typescript
const VideoEmbed = Quill.import("formats/video") as any;

class Video extends VideoEmbed {
    html () {
        return this.domNode.outerHTML;
    }
}

Quill.register(Video, true);
```
