### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by 0312birdzhang** [slab/quill#4287]
So many **table** parser issues reported, and no response.

![image](https://github.com/slab/quill/assets/1762041/922c07ed-c73e-4459-93b7-98b2dc487759)

https://github.com/slab/quill/issues/4262
https://github.com/slab/quill/issues/4209
https://github.com/slab/quill/issues/4181
https://github.com/slab/quill/issues/4166
https://github.com/slab/quill/issues/4125
https://github.com/slab/quill/issues/4102
https://github.com/slab/quill/issues/4023
...

**Comment by jmmrte** [comment]
A bit salty @0312birdzhang, these guys work hard

**Comment by jmmrte** [comment]
Maybe rename this issue to something more constructive, and use it to aggregate all table parser issues in one place?

**Comment by shareefalis** [comment]
Table are a recent feature that the community actually provided to the quill project, it is a brand new 2.0 feature i brelieve and forgive us but you are so salty

**Comment by reqwire** [comment]
I just abandoned Quill for similar reasons. :/
2.0 was a downgrade

**Comment by 0312birdzhang** [comment]
> I just abandoned Quill for similar reasons. :/ 2.0 was a downgrade

Thank you, i tried 1.3.7 and it works better than 2.0.

**Comment by 0312birdzhang** [comment]
@reqwire I switched to Trumbowyg, it works great well.

**Comment by djapal** [comment]
@0312birdzhang thank you for your comment. switched to Trumbowyg too. Lost too much time trying to make it work with importing html that has tables inside....
