### ISSUE TITLE
Problem Selection Methods

### ISSUE THREAD

**Issue by kosowski1** [slab/quill#4293]
When i try to use getSelection method, return "Cannot read properties of null (reading 'offset')",
![image](https://github.com/slab/quill/assets/39204355/5d014f57-620d-430a-8191-aa33e5be3589)

![image](https://github.com/slab/quill/assets/39204355/a88ea7c8-c19c-407e-acc7-de27c8373181)
The blot is returning null

Quill v2.0.2

**Comment by ozgur-proreact** [comment]
@kosowski1 , I was getting the same error on my Vue 3 project. I've noticed that I was using `ref()` for the quill instance variable. That was the issue. Maybe it helps.

**Comment by ozgur-proreact** [comment]
@AcWrong02, frankly I have no idea.
