### ISSUE TITLE
Key listener for Tab doesn't work in quill-mention and ReactQuill

### ISSUE THREAD

**Issue by fatima-nehmeh** [slab/quill#4326]
Hello, I am trying to implement the **quill-mention** with the **ReactQuill** component, but it seems that they're not working. 
I am getting the following error:

_Uncaught TypeError: Cannot read properties of undefined (reading 'unshift')
    at new Mention (mention.ts:327:1) ===> quill.keyboard.bindings[Keys.TAB].unshift(
      quill.keyboard.bindings[Keys.TAB].pop()!
    );_

_Keys.TAB should be 9 but instead it is defined as Tab._

### Here is a look at my code:
```

import {Mention, MentionBlot} from "quill-mention";
 Quill.register({ "blots/mention": MentionBlot, "modules/mention": Mention });

<ReactQuill
                      className="fullscreen-quill"
                      ref={quillRef}
                      name="body"
                      value={descriptionV}
                      onChange={handleQuillChange}
                      readOnly={isEmployee === Mnemonics.ResourceTypes.External}
                      modules={{mention: {
                        allowedChars: /^[A-Za-z\s]*$/,
                        mentionDenotationChars: ["@"],
                        source: async function(searchTerm, renderList) {
                          const matchedPeople = await suggestPeople(searchTerm);
                          renderList(matchedPeople);
                        }
                      }
                    }}
                      formats={formats}
                      placeholder="Description"
                    />
                    
```
                    
                    
 How can I fix this ??

**Comment by shareefalis** [comment]
That module is only compatible with quill 2.0 because you are using Quill  1.3.7 in  Reactquill 2.0. Fork the react Quill Library change library version to 2.0.2 and  fix any compile errors.

**Comment by shareefalis** [comment]
I think @luin should fork the react Quill library and make it official

**Comment by fatima-nehmeh** [comment]
Hey @shareefalis, thank you! 
Now I'm using the react-quill-new component, and it seems to be working but when I choose an option to mention I get the following error:

_[Parchment] Unable to create mention blot
ParchmentError: [Parchment] Unable to create mention blot_

Do you know what might be causing this issue and how to fix it please?

**Comment by fatima-nehmeh** [comment]
Just found out that I need to add "mention" to formats.

Thanks a lot!

I will close this issue : )

**Comment by vinuth-k** [comment]
Can someone drop the working code in the comment .


My code :
import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";
import Quill from "quill";
import {Mention, MentionBlot} from "quill-mention";

Quill.register({ "blots/mention": MentionBlot, "modules/mention": Mention });

 const modules = {
    mention: {
      allowedChars: /^[A-Za-z0-9\s]*$/,  // Allow alphanumeric characters and spaces
      source: function(query, callback) {
        const matches = suggestions.filter(suggestion =>
          suggestion.value.toLowerCase().includes(query.toLowerCase())
        );
        callback(matches);  // Return the matches as suggestions
      },
    },
  };
   <ReactQuill
              theme="snow"
              value={editorContent}
              onChange={handleChange}
              // modules={{ mention: mentionModule.mention }}
              modules={modules}
              style={{ height: "300px", marginBottom: "20px" }}
            />

If I run this I'm getting this error 
Uncaught TypeError: Cannot read properties of undefined (reading 'unshift')
    at new _Mention (chunk-5HT56IPF.js?v=05dd203f:18238:39)
    at SnowTheme2.addModule (chunk-UE2R65KZ.js?v=05dd203f:6045:40)
    at SnowTheme2.addModule (chunk-UE2R65KZ.js?v=05dd203f:6737:136)
    at chunk-UE2R65KZ.js?v=05dd203f:6037:29
    at Array.forEach (<anonymous>)
