### ISSUE TITLE
Quill 2.0 with `attributors/style/font`: cannot use a font whose name ends with numbers after a space

### ISSUE THREAD

**Issue by teedyay** [slab/quill#4342]
I'm using Quill 2.0 with Google Fonts. Generally it works very well, but I notice that fonts whose names end with numbers after a space cannot be used, such as "Source Sans 3", "Jacquard 12". Other font names with spaces are fine ("Times New Roman") and fonts ending with numbers are fine, so long as they don't include a space ("B612").

This is not due to any interaction with Google Fonts: I can reproduce the bug by using the Playground at https://quilljs.com/playground/snow. See the code sample below.

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/snow
2. Copy-paste the code sample below.
3. In the browser console, note how `quill.getContents()` changes (or doesn't) each time a new font is applied.

```
const fontStyle = Quill.import('attributors/style/font');
// Setting the whitelist to undefined allows all fonts. (We don't know what fonts Google Fonts will give us.)
fontStyle.whitelist = undefined;
Quill.register(fontStyle, true);

const quill = new Quill('#editor', {
  theme: 'snow',
});

quill.insertText(0, 'Lorem ipsum');
quill.setSelection(0, 11);

console.log(JSON.stringify(quill.getContents()))
// Output: {"ops":[{"insert":"Lorem ipsum\n"}]}

// Changing font works as expected
quill.format('font', 'Roboto')
console.log(JSON.stringify(quill.getContents()))
// Output: {"ops":[{"attributes":{"font":"Roboto"},"insert":"Lorem ipsum"},{"insert":"\n"}]}

// Using a font whose name ends with numbers works as expected
quill.format('font', 'B612')
console.log(JSON.stringify(quill.getContents()))
// Output: {"ops":[{"attributes":{"font":"B612"},"insert":"Lorem ipsum"},{"insert":"\n"}]}

// Using a font with spaces in the name works as expected
quill.format('font', 'Times New Roman')
console.log(JSON.stringify(quill.getContents()))
// Output: {"ops":[{"attributes":{"font":"Times New Roman"},"insert":"Lorem ipsum"},{"insert":"\n"}]}

// Using a font those name ends with a number after a space does not work: it leaves the font unchanged.
quill.format('font', 'Source Sans 3')
console.log(JSON.stringify(quill.getContents()))
// Output: {"ops":[{"attributes":{"font":"Times New Roman"},"insert":"Lorem ipsum"},{"insert":"\n"}]}

// Using a font those name ends with multiple numbers after a space does not work: it leaves the font unchanged.
quill.format('font', 'Jacquard 12')
console.log(JSON.stringify(quill.getContents()))
// Output: {"ops":[{"attributes":{"font":"Times New Roman"},"insert":"Lorem ipsum"},{"insert":"\n"}]}
```

**Expected behavior**:
Any font name can be used.

**Actual behavior**:
Fonts whose names end with numbers after a space are silently rejected.

**Platforms**:
Google Chrome, PC, Windows 11

**Version**:
2.0.2

**Comment by helgeFox** [comment]
You have to escape the fontFamily value like this
` quill.format('font', '"Source Sans 3"')`
[stackoverflow](https://stackoverflow.com/questions/8951584/assigning-a-css-fontfamily-ending-with-a-number)

**Comment by teedyay** [comment]
Wonderful, thank you! That worked perfectly.

It threw me that my change didn't appear in Quill, so I put it down to that rather than being an HTML thing.

**Comment by teedyay** [comment]
Confirm that putting quotes around the font name works. This is (I guess?) not a bug.
