### ISSUE TITLE
Quill v2.0.2 addBinding with shiftKey does not work on Windows 11.

### ISSUE THREAD

**Issue by drewgman** [slab/quill#4442]
**Steps for Reproduction**

Add custom bindings where `shiftKey` is true using Quill v2.0.2.

```
quill.keyboard?.addBinding(
    { key: 'x' }, 
    { metaKey: true, shiftKey: true }, 
    () => {
        alert("Alert works!")
    }
);

quill.keyboard?.addBinding(
    { key: 'x' }, 
    { altKey: true, shiftKey: true }, 
    () => {
        alert("Alert works!")
    }
);
```

**Expected behavior**:

On a Mac, the combination `cmd + shift + x` will display the alert.
On a Windows machine, the combination `alt + shift + x` will display the alert.

**Actual behavior**:

Only the Mac will display an alert, the binding does not work on Windows.

**Details**:

I tried multiple different combinations of modifier keys on my Windows machine, and pinned it down to `shiftKey` causing the issue. For example:

These _will_ show the alert:

```
{ key: "x", altKey: true }
{ key: "x", altKey: true, ctrlKey: true }
{ key: "x", ctrlKey: true }
{ key: "5", altKey: true }
{ key: "5", altKey: true, ctrlKey: true }
{ key: "5", ctrlKey: true }
```

These _will not_ show the alert:
```
{ key: "x", altKey: true, shiftKey: true }
{ key: "x", ctrlKey: true, shiftKey: true }
{ key: "5", altKey: true, shiftKey: true }
{ key: "5", ctrlKey: true, shiftKey: true }
```

**Platforms**:

Chrome Version 129.0.6668.90 (Official Build) (64-bit)
Windows 11 Home Version 10.0.22631 Build 22631

**Version**:

Quill 2.0.2

**Comment by babu-ch** [comment]
On a Mac, pressing Cmd+Shift+x results in a lowercase "x", but on Windows, it seems to result in an uppercase "X". In other words, for now, you can avoid this issue by specifying the uppercase "X" as the key.


```js
// windows
quill.keyboard?.addBinding(
    { key: 'X' },  
    { altKey: true, shiftKey: true }, 
    () => {
        alert("Alert works!")
    }
);
```

**Comment by drewgman** [comment]
@babu-ch Using the uppercase version key works for me, thanks for catching that! Tested it and it also applies to numeric keys, requiring '%' instead of '5' for example.
