### ISSUE TITLE
Which method should be used instead of pasteHTML after upgrading?

### ISSUE THREAD

**Issue by xxwangkaimin** [slab/quill#4479]
In version 1. x, the pasteHTML method was used to initialize content, but in version 2. x, this method was removed. Which method should I use instead?

**Comment by zoltalar** [comment]
Try this: `quill.clipboard.dangerouslyPasteHTML(html)`

**Comment by xxwangkaimin** [comment]
@zoltalar Thank you very much. I have found a relevant method to replace it.
